### ISSUE TITLE
6.18.1. 安装 GCC 部分 --target=$LFS_TGT翻译少了一个词“之前”

### ISSUE THREAD

**Issue by gengshuhui** [xry111/lfs-book-i18n#39]
--target=$LFS_TGT
由于我们正在交叉编译 GCC，此时不可能用**之前**编译得到的 GCC 二进制程序

https://www.linuxfromscratch.org/lfs/view/development/chapter06/gcc-pass2.html
```
-target=$LFS_TGT
We are cross-compiling GCC, so it's impossible to build target libraries (libgcc and libstdc++) with the previously compiled GCC binaries
```

**Comment by xry111** [comment]
I don't think using "previously" here is correct.  This option makes the building system build target libraries with GCC pass 1, instead of the "just built" GCC pass 2 (if we don't pass --target=$LFS_TGT it'll use GCC pass 2 and the build may fail).  And GCC pass 1 is exactly the "previous" built GCC here (it's prior to GCC pass 2).

I need to contact other LFS editors to see if the English book is just wrong.

**Comment by xry111** [comment]
The English book has been reworded.
